name: build
on:
  push:
    branches: [master1]
jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cross-build
          ./build_binary.sh arm64
