name: cross_arm64
on:
  push:
    tags:
      - T*

jobs:
  multiarch:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'uname -a'
      - name: Check result
        run: |
          docker pull arm64v8/python:buster
          docker run --rm arm64v8/python:buster uname -a
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Avalaible platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Check the result
        run: |
          docker pull arm64v8/python:buster
          docker run --rm arm64v8/python:3.7.10-slim-stretch uname -a
  build-arm64:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Checkout docker/compose repo
        uses: actions/checkout@v2
        with:
          repository: 'docker/compose'
      - name: Checkout this repo into tools/ directory
        uses: actions/checkout@v2
        with:
          path: tools
      - name: Replace the Dockerfile in the docker/compose repo
        run: |
          cp ./tools/Dockerfile ./Dockerfile
          cp ./tools/build_binary.sh ./build_binary.sh
      - name: build
        run: |
          set -ex
          export DOCKER_BUILDKIT=1

          ./script/clean

          DOCKER_COMPOSE_GITSHA="$(script/build/write-git-sha)"
          docker build . \
              -f tools/Dockerfile.build-only \
              --target bin \
              --build-arg DISTRO=debian \
              --build-arg GIT_COMMIT="${DOCKER_COMPOSE_GITSHA}" \
              --build-arg TARGETOS="linux" \
              --output dist/
      - name: Upload the build result
        uses: actions/upload-artifact@v2
        with:
          name: temp-result
          path: dist
  build-native:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker/compose repo
        uses: actions/checkout@v2
        with:
          repository: 'docker/compose'
      - name: Checkout this repo into tools/ directory
        uses: actions/checkout@v2
        with:
          path: tools
      - name: build
        run: |
          set -ex
          export DOCKER_BUILDKIT=1

          ./script/clean

          DOCKER_COMPOSE_GITSHA="$(script/build/write-git-sha)"
          docker build . \
              -f tools/Dockerfile.build-only \
              --target bin \
              --build-arg DISTRO=debian \
              --build-arg GIT_COMMIT="${DOCKER_COMPOSE_GITSHA}" \
              --build-arg TARGETOS="linux" \
              --output dist/
      - name: Upload the build result
        uses: actions/upload-artifact@v2
        with:
          name: temp-result
          path: dist
