name: cross_arm64
on:
  push:
    tags:
      - v*

jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'uname -a'
      - name: Check result
        run: |
          docker pull arm64v8/python
          docker run --rm arm64v8/python uname -a
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Avalaible platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Check the result
        run: |
          docker pull arm64v8/python
          docker run --rm arm64v8/python uname -a
