name: cross_arm64
on:
  push:
    tags:
      - v*

jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Check the result
        run: |
          docker run --rm arm64v8/alpine uname -m
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Avalaible platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Check the result
        run: |
          docker run --rm arm64v8/alpine uname -m
          