name: cross_arm64
on:
  push:
    tags:
      - T*

jobs:
  multiarch:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: 'uname -a'
      - name: Check result
        run: |
          docker pull arm64v8/python:buster
          docker run --rm arm64v8/python:buster uname -a
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Avalaible platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Check the result
        run: |
          docker pull arm64v8/python:buster
          docker run --rm arm64v8/python:buster uname -a
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Active qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Checkout this repo into tools/ directory
        uses: actions/checkout@v2
        with:
          path: 'tools'
      - name: Checkout docker/compose repo
        uses: actions/checkout@v2
        with:
          repository: 'docker/compose'
      - name: Replace the Dockerfile in the docker/compose repo
        run: |
          pwd
          ls -la .
          ls -la ./tools
          cp ./tools/Dockerfile ./Dockerfile
      - name: build
        run: |
          set -ex
          
          ./script/clean

          DOCKER_COMPOSE_GITSHA="$(script/build/write-git-sha)"

          docker build . \
              --build-arg DISTRO=debian \
              --build-arg GIT_COMMIT="${DOCKER_COMPOSE_GITSHA}" \
              --output dist/
          ARCH=$(uname -m)
          pwd
          ls -la .
          ls -la dist
